// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $articles_slug_ from "./routes/articles/[slug].tsx";
import * as $articles_layout from "./routes/articles/_layout.tsx";
import * as $articles_index from "./routes/articles/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $work_together from "./routes/work-together.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $WorkForm from "./islands/WorkForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/articles/[slug].tsx": $articles_slug_,
    "./routes/articles/_layout.tsx": $articles_layout,
    "./routes/articles/index.tsx": $articles_index,
    "./routes/index.tsx": $index,
    "./routes/work-together.tsx": $work_together,
  },
  islands: {
    "./islands/Header.tsx": $Header,
    "./islands/WorkForm.tsx": $WorkForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
